# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            George Kaye
tagline:          'Computer scientist'
description:      'Hello world!'
url:              https://georgejkaye.com
baseurl:          /

author:
  name:           'George Kaye'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/georgejkaye

# Gems
gems: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME