# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            George Kaye
tagline:          'Computer scientist'
description:      'Hello world!'
url:              https://georgejkaye.com
baseurl:          /

author:
  name:           'George Kaye'            
  avatar:         /images/me/me.jpg

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:           https://github.com/georgejkaye
misc:             /misc/

# Gems
plugins: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME