// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../../../node_modules/reason-react/lib/es6_global/src/ReactDOMRe.js";
import * as Interface$CircuitVisualiser from "./Interface.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Interface$CircuitVisualiser.make, { }), "test");

export {
  
}
/*  Not a pure module */
