// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_builtin_exceptions from "../../../node_modules/bs-platform/lib/es6/caml_builtin_exceptions.js";

var simpleLatticeElems = /* :: */[
  /* tuple */[
    0,
    0
  ],
  /* :: */[
    /* tuple */[
      1,
      0
    ],
    /* :: */[
      /* tuple */[
        1,
        1
      ],
      /* :: */[
        /* tuple */[
          2,
          0
        ],
        /* [] */0
      ]
    ]
  ]
];

function simpleLeq(a, b) {
  var exit = 0;
  switch (a[0]) {
    case 0 :
        if (a[1] !== 0) {
          exit = 2;
        } else {
          return true;
        }
        break;
    case 1 :
        var match = a[1];
        if (match !== 0) {
          if (match !== 1 || b[0] !== 1) {
            exit = 2;
          } else if ((b[1] >>> 0) <= 1) {
            return true;
          }
          
        } else if (b[0] !== 1) {
          exit = 2;
        } else if ((b[1] >>> 0) <= 1) {
          return true;
        }
        break;
    case 2 :
        if (a[1] !== 0) {
          exit = 2;
        } else {
          return false;
        }
        break;
    default:
      exit = 2;
  }
  if (exit === 2) {
    var match$1 = b[0];
    switch (match$1) {
      case 0 :
          if (b[1] === 0) {
            return false;
          }
          break;
      case 1 :
          break;
      case 2 :
          if (b[1] === 0) {
            return true;
          }
          break;
      default:
        
    }
  }
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "Lattices.re",
          39,
          26
        ]
      ];
}

function printSimpleLattice(elem) {
  switch (elem[0]) {
    case 0 :
        if (elem[1] === 0) {
          return "\xe2\x8a\xa5";
        }
        break;
    case 1 :
        var match = elem[1];
        if (match !== 0) {
          if (match === 1) {
            return "t";
          }
          
        } else {
          return "f";
        }
        break;
    case 2 :
        if (elem[1] === 0) {
          return "T";
        }
        break;
    default:
      
  }
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "Lattices.re",
          52,
          35
        ]
      ];
}

function simpleJoin(a, b) {
  var match = a[0];
  var exit = 0;
  var exit$1 = 0;
  var exit$2 = 0;
  if (match !== 2 || a[1] !== 0) {
    exit$2 = 4;
  } else {
    return /* tuple */[
            2,
            0
          ];
  }
  if (exit$2 === 4) {
    if (b[0] !== 2 || b[1] !== 0) {
      exit$1 = 3;
    } else {
      return /* tuple */[
              2,
              0
            ];
    }
  }
  if (exit$1 === 3) {
    if (match !== 0 || a[1] !== 0) {
      exit = 2;
    } else {
      return b;
    }
  }
  if (exit === 2 && b[0] === 0 && b[1] === 0) {
    return a;
  }
  if (match !== 1) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Lattices.re",
            61,
            26
          ]
        ];
  }
  var match$1 = a[1];
  if (match$1 !== 0) {
    if (match$1 !== 1) {
      throw [
            Caml_builtin_exceptions.match_failure,
            /* tuple */[
              "Lattices.re",
              61,
              26
            ]
          ];
    } else {
      return /* tuple */[
              1,
              1
            ];
    }
  } else {
    return /* tuple */[
            1,
            0
          ];
  }
}

function simpleMeet(a, b) {
  var match = a[0];
  var exit = 0;
  var exit$1 = 0;
  var exit$2 = 0;
  if (match !== 0 || a[1] !== 0) {
    exit$2 = 4;
  } else {
    return /* tuple */[
            0,
            0
          ];
  }
  if (exit$2 === 4) {
    if (b[0] !== 0 || b[1] !== 0) {
      exit$1 = 3;
    } else {
      return /* tuple */[
              0,
              0
            ];
    }
  }
  if (exit$1 === 3) {
    if (match !== 2 || a[1] !== 0) {
      exit = 2;
    } else {
      return b;
    }
  }
  if (exit === 2 && b[0] === 2 && b[1] === 0) {
    return a;
  }
  if (match !== 1) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Lattices.re",
            72,
            26
          ]
        ];
  }
  var match$1 = a[1];
  if (match$1 !== 0) {
    if (match$1 !== 1) {
      throw [
            Caml_builtin_exceptions.match_failure,
            /* tuple */[
              "Lattices.re",
              72,
              26
            ]
          ];
    } else {
      return /* tuple */[
              1,
              1
            ];
    }
  } else {
    return /* tuple */[
            1,
            0
          ];
  }
}

function simpleAnd(a, b) {
  var match = a[0];
  var exit = 0;
  var exit$1 = 0;
  var exit$2 = 0;
  switch (match) {
    case 0 :
        if (a[1] !== 0) {
          exit$2 = 4;
        } else {
          return /* tuple */[
                  0,
                  0
                ];
        }
        break;
    case 1 :
        exit$2 = 4;
        break;
    case 2 :
        if (a[1] !== 0 || b[0] !== 2) {
          exit$2 = 4;
        } else if (b[1] === 0) {
          return /* tuple */[
                  2,
                  0
                ];
        }
        break;
    default:
      exit$2 = 4;
  }
  if (exit$2 === 4) {
    var match$1 = b[0];
    if (match$1 !== 0) {
      if (match$1 !== 1 || b[1] !== 0) {
        exit$1 = 3;
      } else {
        return /* tuple */[
                1,
                0
              ];
      }
    } else if (b[1] !== 0) {
      exit$1 = 3;
    } else {
      return /* tuple */[
              0,
              0
            ];
    }
  }
  if (exit$1 === 3) {
    if (match !== 1) {
      exit = 2;
    } else {
      var match$2 = a[1];
      if (match$2 !== 0) {
        if (match$2 !== 1) {
          exit = 2;
        } else {
          return b;
        }
      } else {
        return /* tuple */[
                1,
                0
              ];
      }
    }
  }
  if (exit === 2 && b[0] === 1 && b[1] === 1) {
    return a;
  }
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "Lattices.re",
          83,
          25
        ]
      ];
}

function simpleOr(a, b) {
  var match = a[0];
  var exit = 0;
  var exit$1 = 0;
  if (match !== 1) {
    exit$1 = 3;
  } else {
    var match$1 = a[1];
    if (match$1 !== 0) {
      if (match$1 !== 1) {
        exit$1 = 3;
      } else {
        return /* tuple */[
                1,
                1
              ];
      }
    } else if (b[0] !== 1 || b[1] !== 0) {
      exit$1 = 3;
    } else {
      return /* tuple */[
              1,
              0
            ];
    }
  }
  if (exit$1 === 3) {
    var match$2 = b[0];
    if (match$2 !== 0) {
      if (match$2 !== 1 || b[1] !== 1) {
        exit = 2;
      } else {
        return /* tuple */[
                1,
                1
              ];
      }
    } else if (b[1] !== 0) {
      exit = 2;
    } else {
      return /* tuple */[
              0,
              0
            ];
    }
  }
  if (exit === 2) {
    switch (match) {
      case 0 :
          if (a[1] === 0) {
            return /* tuple */[
                    0,
                    0
                  ];
          }
          break;
      case 1 :
          break;
      case 2 :
          if (a[1] === 0) {
            return /* tuple */[
                    2,
                    0
                  ];
          }
          break;
      default:
        
    }
  }
  if (b[0] !== 2) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Lattices.re",
            95,
            24
          ]
        ];
  }
  if (b[1] !== 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Lattices.re",
            95,
            24
          ]
        ];
  } else {
    return /* tuple */[
            2,
            0
          ];
  }
}

function simpleNot(a) {
  switch (a[0]) {
    case 0 :
        if (a[1] === 0) {
          return /* tuple */[
                  0,
                  0
                ];
        }
        break;
    case 1 :
        var match = a[1];
        if (match !== 0) {
          if (match === 1) {
            return /* tuple */[
                    1,
                    0
                  ];
          }
          
        } else {
          return /* tuple */[
                  1,
                  1
                ];
        }
        break;
    case 2 :
        if (a[1] === 0) {
          return /* tuple */[
                  2,
                  0
                ];
        }
        break;
    default:
      
  }
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "Lattices.re",
          107,
          21
        ]
      ];
}

function simpleParse(str) {
  switch (str) {
    case "B" :
        return /* tuple */[
                true,
                /* tuple */[
                  0,
                  0
                ]
              ];
    case "T" :
        return /* tuple */[
                true,
                /* tuple */[
                  2,
                  0
                ]
              ];
    case "f" :
        return /* tuple */[
                true,
                /* tuple */[
                  1,
                  0
                ]
              ];
    case "t" :
        return /* tuple */[
                true,
                /* tuple */[
                  1,
                  1
                ]
              ];
    default:
      return /* tuple */[
              false,
              /* tuple */[
                2,
                0
              ]
            ];
  }
}

var simpleLattice_highValues = /* :: */[
  /* tuple */[
    1,
    1
  ],
  /* [] */0
];

var simpleLattice = {
  elems: simpleLatticeElems,
  highValues: simpleLattice_highValues,
  leq: simpleLeq,
  joinOp: simpleJoin,
  meetOp: simpleMeet,
  andOp: simpleAnd,
  orOp: simpleOr,
  notOp: simpleNot,
  print: printSimpleLattice,
  parse: simpleParse
};

function getLattice(lat) {
  return simpleLatticeElems;
}

var bot = /* tuple */[
  0,
  0
];

var t = /* tuple */[
  1,
  1
];

var f = /* tuple */[
  1,
  0
];

var top = /* tuple */[
  2,
  0
];

export {
  simpleLatticeElems ,
  bot ,
  t ,
  f ,
  top ,
  simpleLeq ,
  printSimpleLattice ,
  simpleJoin ,
  simpleMeet ,
  simpleAnd ,
  simpleOr ,
  simpleNot ,
  simpleParse ,
  simpleLattice ,
  getLattice ,
  
}
/* No side effect */
