// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function str(prim) {
  return prim;
}

function log(param) {
  console.log("Hey there!");
  return /* () */0;
}

export {
  str ,
  log ,
  
}
/* No side effect */
