name: Eleventy build
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build:eleventy
      - name: Compile sass
        run: yarn build:sass
      - name: Push to main branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd ${{ vars.PROJECT_REPO }}
            git pull
            cp -r * ${{ vars.SITE_DIRECTORY }}
            rm -rf ${{ vars.SITE_DIRECTORY }}/.git

