name: Eleventy build

on:
  push:
    branches: [ eleventy ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build:eleventy
      - name: Compile sass
        run: yarn build:sass
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: build 
          PUBLISH_BRANCH: eleventy-test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
